import localFont from "next/font/local";
import "./globals.css";
import App from "@/components/App";
import StoreProvider from "@/redux/storeProvider";

const vazirFont = localFont({
  src: [
    {
      path: "../font/Vazir-FD-WOL.woff2", // Ensure this path is correct
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${vazirFont.className} bg-slate-950 text-slate-100`}>
        <StoreProvider>
          <App>{children}</App>
        </StoreProvider>
      </body>
    </html>
  );
}
